//------------------------------------------------------------------------------
//  MACHINE GENERATED, DON'T EDIT!
//------------------------------------------------------------------------------
#include "stdneb.h"
#include "graphicsprotocol.h"


namespace Graphics
{
    __ImplementClass(Graphics::RegisterRTPlugin, 'RRTP', Messaging::Message);
    __ImplementMsgId(RegisterRTPlugin);
    __ImplementClass(Graphics::UnregisterRTPlugin, 'URTP', Messaging::Message);
    __ImplementMsgId(UnregisterRTPlugin);
    __ImplementClass(Graphics::SetupGraphics, 'SUPG', Messaging::Message);
    __ImplementMsgId(SetupGraphics);
    __ImplementClass(Graphics::UpdateDisplay, 'INDS', Messaging::Message);
    __ImplementMsgId(UpdateDisplay);
    __ImplementClass(Graphics::PostWindowEvent, 'POEV', Messaging::Message);
    __ImplementMsgId(PostWindowEvent);
    __ImplementClass(Graphics::EnableResourcesAsync, 'REAS', Messaging::Message);
    __ImplementMsgId(EnableResourcesAsync);
    __ImplementClass(Graphics::ReloadResource, 'RLRC', Messaging::Message);
    __ImplementMsgId(ReloadResource);
    __ImplementClass(Graphics::ReloadResourceIfExists, 'RRIE', Messaging::Message);
    __ImplementMsgId(ReloadResourceIfExists);
    __ImplementClass(Graphics::EnablePicking, 'ENPI', Messaging::Message);
    __ImplementMsgId(EnablePicking);
    __ImplementClass(Graphics::SetEnvironmentAttached, 'SENA', Messaging::Message);
    __ImplementMsgId(SetEnvironmentAttached);
    __ImplementClass(Graphics::ItemAtPosition, 'ITAP', Messaging::Message);
    __ImplementMsgId(ItemAtPosition);
    __ImplementClass(Graphics::ItemsAtPosition, 'ISAP', Messaging::Message);
    __ImplementMsgId(ItemsAtPosition);
    __ImplementClass(Graphics::DepthAtPosition, 'DPAP', Messaging::Message);
    __ImplementMsgId(DepthAtPosition);
    __ImplementClass(Graphics::NormalAtPosition, 'NOAP', Messaging::Message);
    __ImplementMsgId(NormalAtPosition);
    __ImplementClass(Graphics::EnableWireframe, 'WIRE', Messaging::Message);
    __ImplementMsgId(EnableWireframe);
    __ImplementClass(Graphics::GetRenderMaterials, 'GRMM', Messaging::Message);
    __ImplementMsgId(GetRenderMaterials);
    __ImplementClass(Graphics::SetModelNodeTexture, 'SMNT', Messaging::Message);
    __ImplementMsgId(SetModelNodeTexture);
    __ImplementClass(Graphics::SetModelNodeVariable, 'SMNV', Messaging::Message);
    __ImplementMsgId(SetModelNodeVariable);
    __ImplementClass(Graphics::AdapterExists, 'AEXT', Messaging::Message);
    __ImplementMsgId(AdapterExists);
    __ImplementClass(Graphics::GetAvailableDisplayModes, 'GADM', Messaging::Message);
    __ImplementMsgId(GetAvailableDisplayModes);
    __ImplementClass(Graphics::SupportsDisplayMode, 'SPDM', Messaging::Message);
    __ImplementMsgId(SupportsDisplayMode);
    __ImplementClass(Graphics::GetCurrentAdapterDisplayMode, 'GCDM', Messaging::Message);
    __ImplementMsgId(GetCurrentAdapterDisplayMode);
    __ImplementClass(Graphics::GetAdapterInfo, 'GADI', Messaging::Message);
    __ImplementMsgId(GetAdapterInfo);
    __ImplementClass(Graphics::AttachDisplayEventHandler, 'ADEH', Messaging::Message);
    __ImplementMsgId(AttachDisplayEventHandler);
    __ImplementClass(Graphics::RemoveDisplayEventHandler, 'RDEH', Messaging::Message);
    __ImplementMsgId(RemoveDisplayEventHandler);
    __ImplementClass(Graphics::AttachRenderEventHandler, 'AREH', Messaging::Message);
    __ImplementMsgId(AttachRenderEventHandler);
    __ImplementClass(Graphics::RemoveRenderEventHandler, 'RREH', Messaging::Message);
    __ImplementMsgId(RemoveRenderEventHandler);
    __ImplementClass(Graphics::CreateGraphicsStage, 'CGST', Messaging::Message);
    __ImplementMsgId(CreateGraphicsStage);
    __ImplementClass(Graphics::DiscardGraphicsStage, 'DIGS', Messaging::Message);
    __ImplementMsgId(DiscardGraphicsStage);
    __ImplementClass(Graphics::CreateGraphicsView, 'CGVW', Messaging::Message);
    __ImplementMsgId(CreateGraphicsView);
    __ImplementClass(Graphics::DiscardGraphicsView, 'DGVW', Messaging::Message);
    __ImplementMsgId(DiscardGraphicsView);
    __ImplementClass(Graphics::SetDefaultGraphicsView, 'SGVW', Messaging::Message);
    __ImplementMsgId(SetDefaultGraphicsView);
    __ImplementClass(Graphics::CreateGraphicsEntity, 'CGET', Messaging::Message);
    __ImplementMsgId(CreateGraphicsEntity);
    __ImplementClass(Graphics::GetModelNodes, 'GGNM', Messaging::Message);
    __ImplementMsgId(GetModelNodes);
    __ImplementClass(Graphics::GetBoundingBox, 'GBOX', Messaging::Message);
    __ImplementMsgId(GetBoundingBox);
    __ImplementClass(Graphics::CreateModelEntity, 'CMDE', CreateGraphicsEntity);
    __ImplementMsgId(CreateModelEntity);
    __ImplementClass(Graphics::CreateCameraEntity, 'CPCE', CreateGraphicsEntity);
    __ImplementMsgId(CreateCameraEntity);
    __ImplementClass(Graphics::CreateGlobalLightEntity, 'CGLE', CreateGraphicsEntity);
    __ImplementMsgId(CreateGlobalLightEntity);
    __ImplementClass(Graphics::CreateSpotLightEntity, 'CSLE', CreateGraphicsEntity);
    __ImplementMsgId(CreateSpotLightEntity);
    __ImplementClass(Graphics::CreatePointLightEntity, 'CPLE', CreateGraphicsEntity);
    __ImplementMsgId(CreatePointLightEntity);
    __ImplementClass(Graphics::CreateBillboardEntity, 'CBBE', CreateGraphicsEntity);
    __ImplementMsgId(CreateBillboardEntity);
    __ImplementClass(Graphics::GraphicsEntityMessage, 'GEMG', Messaging::Message);
    __ImplementMsgId(GraphicsEntityMessage);
    __ImplementClass(Graphics::DiscardGraphicsEntity, 'DCGE', GraphicsEntityMessage);
    __ImplementMsgId(DiscardGraphicsEntity);
    __ImplementClass(Graphics::AddTrackedCharJoint, 'ATCJ', GraphicsEntityMessage);
    __ImplementMsgId(AddTrackedCharJoint);
    __ImplementClass(Graphics::SetLightColor, 'SLCL', GraphicsEntityMessage);
    __ImplementMsgId(SetLightColor);
    __ImplementClass(Graphics::SetLightCastShadows, 'SLCS', GraphicsEntityMessage);
    __ImplementMsgId(SetLightCastShadows);
    __ImplementClass(Graphics::SetLightShadowIntensity, 'SSIN', GraphicsEntityMessage);
    __ImplementMsgId(SetLightShadowIntensity);
    __ImplementClass(Graphics::SetLightShadowBias, 'SSSB', GraphicsEntityMessage);
    __ImplementMsgId(SetLightShadowBias);
    __ImplementClass(Graphics::SetGlobalBackLightColor, 'SGBL', GraphicsEntityMessage);
    __ImplementMsgId(SetGlobalBackLightColor);
    __ImplementClass(Graphics::SetGlobalAmbientLightColor, 'SGAL', GraphicsEntityMessage);
    __ImplementMsgId(SetGlobalAmbientLightColor);
    __ImplementClass(Graphics::SetGlobalBackLightOffset, 'SGBO', GraphicsEntityMessage);
    __ImplementMsgId(SetGlobalBackLightOffset);
    __ImplementClass(Graphics::SetGlobalLightShadowArea, 'SGLA', GraphicsEntityMessage);
    __ImplementMsgId(SetGlobalLightShadowArea);
    __ImplementClass(Graphics::SetLightVolumetric, 'SLRV', GraphicsEntityMessage);
    __ImplementMsgId(SetLightVolumetric);
    __ImplementClass(Graphics::SetLightVolumetricScale, 'SLVS', GraphicsEntityMessage);
    __ImplementMsgId(SetLightVolumetricScale);
    __ImplementClass(Graphics::SetLightVolumetricIntensity, 'SLVI', GraphicsEntityMessage);
    __ImplementMsgId(SetLightVolumetricIntensity);
    __ImplementClass(Graphics::SetGlobalLightParams, 'SGLP', GraphicsEntityMessage);
    __ImplementMsgId(SetGlobalLightParams);
    __ImplementClass(Graphics::SetRenderSkeleton, 'SRSK', GraphicsEntityMessage);
    __ImplementMsgId(SetRenderSkeleton);
    __ImplementClass(Graphics::SetGlobalLightColor, 'SGLC', GraphicsEntityMessage);
    __ImplementMsgId(SetGlobalLightColor);
    __ImplementClass(Graphics::SetLightProjectionTexture, 'SLPT', GraphicsEntityMessage);
    __ImplementMsgId(SetLightProjectionTexture);
    __ImplementClass(Graphics::UpdateTransform, 'SETR', GraphicsEntityMessage);
    __ImplementMsgId(UpdateTransform);
    __ImplementClass(Graphics::SetVisibility, 'SVSB', GraphicsEntityMessage);
    __ImplementMsgId(SetVisibility);
    __ImplementClass(Graphics::AttachCameraToView, 'ACTV', GraphicsEntityMessage);
    __ImplementMsgId(AttachCameraToView);
    __ImplementClass(Graphics::RemoveCameraFromView, 'RCFV', GraphicsEntityMessage);
    __ImplementMsgId(RemoveCameraFromView);
    __ImplementClass(Graphics::UpdModelNodeInstanceMaterialVariable, 'UISV', GraphicsEntityMessage);
    __ImplementMsgId(UpdModelNodeInstanceMaterialVariable);
    __ImplementClass(Graphics::UpdModelNodeInstanceVisibility, 'SMSV', GraphicsEntityMessage);
    __ImplementMsgId(UpdModelNodeInstanceVisibility);
    __ImplementClass(Graphics::UpdateSharedShaderVariable, 'USSV', Messaging::Message);
    __ImplementMsgId(UpdateSharedShaderVariable);
    __ImplementClass(Graphics::SetOverlayColor, 'SOCL', GraphicsEntityMessage);
    __ImplementMsgId(SetOverlayColor);
    __ImplementClass(Graphics::AnimPlayClip, 'ANPC', GraphicsEntityMessage);
    __ImplementMsgId(AnimPlayClip);
    __ImplementClass(Graphics::FetchClips, 'ANGC', GraphicsEntityMessage);
    __ImplementMsgId(FetchClips);
    __ImplementClass(Graphics::AnimStopTrack, 'ASTR', GraphicsEntityMessage);
    __ImplementMsgId(AnimStopTrack);
    __ImplementClass(Graphics::AnimStopAllTracks, 'ASAT', GraphicsEntityMessage);
    __ImplementMsgId(AnimStopAllTracks);
    __ImplementClass(Graphics::AnimPauseTrack, 'ANPT', GraphicsEntityMessage);
    __ImplementMsgId(AnimPauseTrack);
    __ImplementClass(Graphics::AnimPauseAllTracks, 'APAT', GraphicsEntityMessage);
    __ImplementMsgId(AnimPauseAllTracks);
    __ImplementClass(Graphics::AnimSeek, 'ANSE', GraphicsEntityMessage);
    __ImplementMsgId(AnimSeek);
    __ImplementClass(Graphics::AnimTime, 'ANTI', GraphicsEntityMessage);
    __ImplementMsgId(AnimTime);
    __ImplementClass(Graphics::AnimModifyBlendWeight, 'ANMB', GraphicsEntityMessage);
    __ImplementMsgId(AnimModifyBlendWeight);
    __ImplementClass(Graphics::AnimModifyTimeFactor, 'ANMT', GraphicsEntityMessage);
    __ImplementMsgId(AnimModifyTimeFactor);
    __ImplementClass(Graphics::AnimIsClipPlaying, 'AISP', GraphicsEntityMessage);
    __ImplementMsgId(AnimIsClipPlaying);
    __ImplementClass(Graphics::ApplySkinList, 'ASKL', GraphicsEntityMessage);
    __ImplementMsgId(ApplySkinList);
    __ImplementClass(Graphics::FetchSkinList, 'GSKL', GraphicsEntityMessage);
    __ImplementMsgId(FetchSkinList);
    __ImplementClass(Graphics::ShowSkin, 'SWSK', GraphicsEntityMessage);
    __ImplementMsgId(ShowSkin);
    __ImplementClass(Graphics::HideSkin, 'HDSK', GraphicsEntityMessage);
    __ImplementMsgId(HideSkin);
    __ImplementClass(Graphics::SetVariation, 'SEVA', GraphicsEntityMessage);
    __ImplementMsgId(SetVariation);
    __ImplementClass(Graphics::SetTimeFactor, 'STIF', Messaging::Message);
    __ImplementMsgId(SetTimeFactor);
    __ImplementClass(Graphics::UnbindAttachment, 'CLAT', GraphicsEntityMessage);
    __ImplementMsgId(UnbindAttachment);
    __ImplementClass(Graphics::BindAttachment, 'ATEN', UnbindAttachment);
    __ImplementMsgId(BindAttachment);
    __ImplementClass(Graphics::SwitchAttachmentToNewJoint, 'SWAT', BindAttachment);
    __ImplementMsgId(SwitchAttachmentToNewJoint);
    __ImplementClass(Graphics::BaseAnimEventMessage, 'BEAV', GraphicsEntityMessage);
    __ImplementMsgId(BaseAnimEventMessage);
    __ImplementClass(Graphics::RegisterAnimEventHandler, 'REAH', Messaging::Message);
    __ImplementMsgId(RegisterAnimEventHandler);
    __ImplementClass(Graphics::UnregisterAnimEventHandler, 'UREH', Messaging::Message);
    __ImplementMsgId(UnregisterAnimEventHandler);
    __ImplementClass(Graphics::PreloadMousePointerTextures, 'PLPT', Messaging::Message);
    __ImplementMsgId(PreloadMousePointerTextures);
    __ImplementClass(Graphics::UpdateMousePointers, 'UNPT', Messaging::Message);
    __ImplementMsgId(UpdateMousePointers);
    __ImplementClass(Graphics::HoldSharedResources, 'HORE', Messaging::Message);
    __ImplementMsgId(HoldSharedResources);
    __ImplementClass(Graphics::ReleaseSharedResources, 'RLRE', Messaging::Message);
    __ImplementMsgId(ReleaseSharedResources);
    __ImplementClass(Graphics::SetAnimatorTime, 'SAFR', GraphicsEntityMessage);
    __ImplementMsgId(SetAnimatorTime);
    __ImplementClass(Graphics::UpdateCameraEntity, 'UPCE', GraphicsEntityMessage);
    __ImplementMsgId(UpdateCameraEntity);
    __ImplementClass(Graphics::SetShadowPointOfInterest, 'SSPO', Messaging::Message);
    __ImplementMsgId(SetShadowPointOfInterest);
    __ImplementClass(Graphics::SetParticleSystemPlaying, 'SPSP', GraphicsEntityMessage);
    __ImplementMsgId(SetParticleSystemPlaying);
    __ImplementClass(Graphics::ToggleParticleSystemPlaying, 'TPSP', GraphicsEntityMessage);
    __ImplementMsgId(ToggleParticleSystemPlaying);
    __ImplementClass(Graphics::ShowSystemCursor, 'SSCU', Messaging::Message);
    __ImplementMsgId(ShowSystemCursor);
} // Graphics

namespace Commands
{
} // namespace Commands
//------------------------------------------------------------------------------
