/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : antlr/grammar/AnyFX.g
 *     -                            On : 2015-07-05 22:33:39
 *     -                 for the lexer : AnyFXLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
AnyFXLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pAnyFXLexer, which is returned from a call to AnyFXLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pAnyFXLexer are  as follows:
 *
 *  - 
 void
      pAnyFXLexer->T__48(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__49(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__50(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__51(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__52(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__53(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__54(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__55(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__56(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__57(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__58(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__59(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__60(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__61(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__62(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__63(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->T__64(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->SC(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->CO(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->COL(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->LP(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->RP(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->LB(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->RB(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->LL(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->RR(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->DOT(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->NOT(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->EQ(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->QO(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->QU(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->AND(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->OR(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->Q(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->NU(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->FORWARDSLASH(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->LESS(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->LESSEQ(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->GREATER(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->GREATEREQ(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->LOGICEQ(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->NOTEQ(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->LOGICAND(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->LOGICOR(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->MOD(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->ADD(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->SUB(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->DIV(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->MUL(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->INTEGER(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->INTEGERLITERAL(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->COMMENT(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->ML_COMMENT(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->FLOATLITERAL(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->EXPONENT(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->DOUBLELITERAL(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->HEX(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->ALPHABET(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->IDENTIFIER(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->PREPROCESSOR(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->WS(pAnyFXLexer)
 *  - 
 void
      pAnyFXLexer->Tokens(pAnyFXLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_AnyFXLexer_H
#define _AnyFXLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#include <string>
struct LexerErrorPackage
{
	std::string file;
};


#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct AnyFXLexer_Ctx_struct AnyFXLexer, * pAnyFXLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
AnyFXLexer

 */
struct AnyFXLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__48)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__49)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__50)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__51)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__52)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__53)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__54)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__55)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__56)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__57)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__58)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__59)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__60)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__61)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__62)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__63)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mT__64)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mSC)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mCO)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mCOL)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mLP)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mRP)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mLB)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mRB)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mLL)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mRR)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mDOT)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mNOT)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mEQ)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mQO)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mQU)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mAND)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mOR)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mQ)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mNU)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mFORWARDSLASH)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mLESS)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mLESSEQ)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mGREATER)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mGREATEREQ)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mLOGICEQ)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mNOTEQ)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mLOGICAND)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mLOGICOR)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mMOD)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mADD)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mSUB)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mDIV)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mMUL)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mINTEGER)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mINTEGERLITERAL)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mML_COMMENT)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mFLOATLITERAL)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mEXPONENT)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mDOUBLELITERAL)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mHEX)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mALPHABET)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mIDENTIFIER)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mPREPROCESSOR)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct AnyFXLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct AnyFXLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct AnyFXLexer_Ctx_struct * ctx);
    void	    (*free)   (struct AnyFXLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pAnyFXLexer AnyFXLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pAnyFXLexer AnyFXLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__59      59
#define T__60      60
#define T__61      61
#define T__62      62
#define T__63      63
#define T__64      64
#define ADD      4
#define ALPHABET      5
#define AND      6
#define CO      7
#define COL      8
#define COMMENT      9
#define DIV      10
#define DOT      11
#define DOUBLELITERAL      12
#define EQ      13
#define EXPONENT      14
#define FLOATLITERAL      15
#define FORWARDSLASH      16
#define GREATER      17
#define GREATEREQ      18
#define HEX      19
#define IDENTIFIER      20
#define INTEGER      21
#define INTEGERLITERAL      22
#define LB      23
#define LESS      24
#define LESSEQ      25
#define LL      26
#define LOGICAND      27
#define LOGICEQ      28
#define LOGICOR      29
#define LP      30
#define ML_COMMENT      31
#define MOD      32
#define MUL      33
#define NOT      34
#define NOTEQ      35
#define NU      36
#define OR      37
#define PREPROCESSOR      38
#define Q      39
#define QO      40
#define QU      41
#define RB      42
#define RP      43
#define RR      44
#define SC      45
#define SUB      46
#define WS      47
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for AnyFXLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
